WIP - Webpacker 3 to Shakapacker 6
shakacode/react-rails-example-app pull request #1
Opened 2023-04-25 11:26 UTC by ahangarha

In this PR, I have updated the project to use Shakapacker 6 instead of Webpacker 3.

Note: This PR is not ready for merge. SSR doesn't work since we need changes in react-rails to support SSR with Shakapacker 6. (PR https://github.com/reactjs/react-rails/pull/1252)

2023-08-02 02:04 UTC, Judahmeek requested changes
I've got some questions.

2023-08-02 02:04 UTC, Judahmeek commented on .gitignore
> +/node_modules
Why is this duplicated on lines 24-26?

2023-08-02 02:04 UTC, Judahmeek commented on app/views/layouts/application.html.erb
> +    <%= javascript_pack_tag "application" %>
Why is `application` in both the `javascript_include_tag` & `javascript_pack_tag`?

2023-08-02 02:04 UTC, Judahmeek commented on config/initializers/assets.rb
> +Rails.application.config.assets.paths << Rails.root.join('node_modules')
Why was this added?

2023-08-02 07:48 UTC, justin808 commented
@Judahmeek can review and merge.

2023-08-02 16:45 UTC, ahangarha commented on .gitignore
> +/node_modules
It must be coming from some rebase 🤔

2023-08-02 17:06 UTC, ahangarha commented
@Judahmeek 
Thanks for the review.

I am wondering why those duplicate lines were added. Since it was a long time ago since I started working on this PR, I don't remember what I was doing at that time.

We get some deprecation warnings in the terminal, and I believe it is because this project uses Rails 5. Do you think it should be fixed in this PR or it can have another PR?

2023-08-10 08:21 UTC, justin808 requested changes

2023-08-10 08:21 UTC, justin808 commented on .nvmrc
> +14
why old version?

2023-08-10 08:21 UTC, justin808 commented on Gemfile
> +gem "rails", "~> 5.2"
v6?

2023-08-10 08:21 UTC, justin808 commented on Gemfile
> +# gem 'sassc-rails'
remove dead coee?

2023-08-10 08:21 UTC, justin808 commented on bin/yarn
> +APP_ROOT = File.expand_path("..", __dir__)
why is this file not deleted?

2023-08-10 08:21 UTC, justin808 commented on config/webpack/clientWebpackConfig.js
> +module.exports = configureClient
no eol at eof

2023-08-10 08:21 UTC, justin808 commented on config/webpack/serverWebpackConfig.js
> +module.exports = configureServer
fix the red dots!

2023-08-10 08:25 UTC, ahangarha commented on Gemfile
> +gem "rails", "~> 5.2"
All in one PR?
I thought Upgrading Rails could and should have its own PR. And this little change was to make it possible to build the project. I don't remember now but there was an issue with Rails < 5.2. I couldn't run the app.

2023-08-10 18:14 UTC, ahangarha commented on bin/yarn
> +APP_ROOT = File.expand_path("..", __dir__)
Even in Shakapacker, we still have this file.

2023-08-10 18:26 UTC, ahangarha commented on .nvmrc
> +14
I removed the file.

2023-08-22 04:05 UTC, merged